apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-default
  namespace: default
spec:
  instances: 1
  storage:
    size: 2Gi
  managed:
    roles:
      - name: coder
        ensure: present
        comment: Coder
        passwordSecret:
         name: coder-creds
