apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  values:
    sources:
      - service
      - traefik-proxy
    provider:
      name: pihole
    domainFilters:
      - homelab.local
    txtOwnerId: prod-external-dns
    registry: noop
    extraArgs:
      - --source=service
      - --source=traefik-proxy
      - --pihole-api-version=6
      - --pihole-server=http://192.168.0.21
    pihole:
      server: 192.168.0.21
      secretName: pihole-password
