apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../traefik
  - ../../external-dns
  - ../../cert-manager
  - cert-manager-clusterissuer-internalca.yaml
patchesStrategicMerge:
  - external-dns-values-patch.yaml
