apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - traefik-dashboard-ingressroute.yaml
  - metallb-config.yaml
  - ../../external-dns
  - ../../traefik
  - longhorn-ingress.yaml
  - creds.yaml
patchesStrategicMerge:
  - traefik-helmrelease-patch.yaml
