apiVersion: v1
kind: Service
metadata:
  name: ttyd
  namespace: devenv
  annotations:
    load-balancer.hetzner.cloud/network-zone: eu-central
spec:
  selector:
    app: ttyd
  ports:
    - port: 7681
      targetPort: 7681
