apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  values:
    provider:
      name: cloudflare
    domainFilters:
      - staging.sneakysquid.xyz
    txtOwnerId: staging-external-dns
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-token
            key: api-token
