apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  values:
    service:
      type: LoadBalancer
      annotations:
        external-dns.alpha.kubernetes.io/hostname: traefik.staging.sneakysquid.xyz
        load-balancer.hetzner.cloud/network-zone: eu-central
        load-balancer.hetzner.cloud/use-private-ip: "true"
